version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
    groups:
      rust-patch-and-minor:
        patterns:
          - "*"
        update-types:
          - patch
          - minor
      rust-major:
        patterns:
          - "*"
        update-types:
          - major
    commit-message:
      prefix: deps

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "09:00"
      timezone: America/Los_Angeles
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: ci
