[package]
name = "tongues-emotions"
version = "0.1.0"
license.workspace = true
edition = "2021"

[dependencies]
anyhow.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tongues-audio = { path = "../tongues-audio" }
tongues-interpretation = { path = "../tongues-interpretation" }
tongues-neural = { path = "../tongues-neural" }
