[package]
name = "tongues-audio"
version = "0.1.0"
license.workspace = true
edition = "2021"

[dependencies]
hound = { workspace = true }
rustfft = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
speaking = { path = "../speaking" }
thiserror = { workspace = true }
