[package]
name = "tongues-audio"
version = "0.1.0"
license.workspace = true
edition = "2021"

[features]
default = ["vad-webrtc", "system-audio"]
vad-webrtc = ["dep:webrtc-vad"]
system-audio = ["dep:cpal"]

[dependencies]
cpal = { workspace = true, optional = true }
hound = { workspace = true }
rustfft = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
speaking = { path = "../speaking" }
thiserror = { workspace = true }
webrtc-vad = { version = "0.4", optional = true }
