[package]
name = "tongues-server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
axum = "0.8.9"
axum-server = { version = "0.7.3", features = ["tls-rustls"] }
burn.workspace = true
burn-cuda.workspace = true
clap.workspace = true
dirs.workspace = true
hound.workspace = true
serde.workspace = true
serde_json.workspace = true
rustls = { version = "0.23.40", features = ["aws-lc-rs"] }
speaking = { version = "0.1.0", path = "../speaking" }
styletts2 = { version = "0.1.0", path = "../styletts2" }
tongues-duplex = { version = "0.1.0", path = "../tongues-duplex" }
tongues-tts = { version = "0.1.0", path = "../tongues-tts" }
tokio = { version = "1.52.3", features = ["full"] }
tokio-stream = { version = "0.1.17", features = ["sync"] }
tower-http = { version = "0.7.0", features = ["fs", "cors"] }
uuid = { version = "1.23.3", features = ["v4"] }
